apiVersion: v1
kind: Pod
metadata:
  name: client-busybox
  namespace: default
  labels:
    app: tetragon-demo
spec:
  containers:
  - name: busybox
    image: busybox:latest
    command: ["sleep", "3600"]
    securityContext:
      capabilities:
        add: ["NET_RAW"]
