apiVersion: v1
kind: Pod
metadata:
  name: client-curl
  namespace: default
  labels:
    app: tetragon-demo
spec:
  containers:
  - name: curl
    image: curlimages/curl:latest
    command: ["sleep", "3600"]
