apiVersion: v1
kind: Pod
metadata:
  name: client-strace
  namespace: default
  labels:
    app: tetragon-demo
    tetragon-demo: strace
spec:
  containers:
  - name: strace
    image: alpine:latest
    command: ["sleep", "3600"]
