apiVersion: v1
kind: Service
metadata:
  name: server-nginx
  namespace: default
spec:
  selector:
    app: tetragon-demo
    tetragon-demo: server
  ports:
  - port: 80
    targetPort: 80
