apiVersion: v1
kind: Pod
metadata:
  name: server-nginx
  namespace: default
  labels:
    app: tetragon-demo
    tetragon-demo: server
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
