apiVersion: v1
kind: Pod
metadata:
  name: nginx-debug
  namespace: team-web
spec:
  containers:
  - name: nginx
    image: nginx:1.25-alpine
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
