apiVersion: v1
kind: Secret
metadata:
  name: proxy-01
  namespace: team-magenta
stringData:
  token: "686501a5"
---
apiVersion: v1
kind: Secret
metadata:
  name: proxy-02
  namespace: team-magenta
stringData:
  token: "9b2c7de3"
---
apiVersion: v1
kind: Secret
metadata:
  name: proxy-03
  namespace: team-magenta
stringData:
  token: "a1f4e8c2"
