apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-manual
  namespace: team-green
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-manual
