apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-signer-csr
subjects:
- kind: ServiceAccount
  name: cert-signer
  namespace: team-lilac
roleRef:
  kind: ClusterRole
  name: cert-signer-csr
  apiGroup: rbac.authorization.k8s.io
