apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: process-exec
spec:
  podSelector:
    matchLabels:
      app: tetragon-demo
  kprobes:
  - call: "security_bprm_creds_from_file"
    syscall: false
    args:
    - index: 0
      type: "nop"
    - index: 1
      type: "file"
