apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: sys-mount
spec:
  podSelector:
    matchLabels:
      app: tetragon-demo
  kprobes:
  - call: "sys_mount"
    syscall: true
    args:
    - index: 0
      type: "string"
    - index: 1
      type: "string"
